### ISSUE TITLE
Schema_info Returning Non Schema Keyword

### ISSUE THREAD

**Issue by PaulHuwe** [asdf-format/asdf#1807] opened 2024-07-20 05:30 UTC
# Description of the problem

When running `schema_info('archive_catalog')` on TVAC data files, some extra metadata (that has no schema) is included when it shouldn't be. This is causing failures in archive catalog scripts.

# Example of the problem

With a sample file, the following keyword is included in the output of `schema_info('archive_catalog')`:
```
>>> archive_catalog['roman']['hdf5_telemetry_attrs']['filename']
{'archive_catalog': {'datatype': 'nvarchar(120)', 'destination': ['WFICommon.filename']}}
```
The `hdf5_telemetry_attrs` group has no schema, and thus should not have an archive catalog destination. File will be provided.

# System information

asdf version: 3.3.0
python version: 3.12.3
operating system: OSX

**Comment by braingram** [comment] 2024-07-20 13:11
Thanks for opening the issue and please do share the file.

Are you also able to share the code that produced the file? My suspicion is that a `roman_datamodels.stnode.Filename` (perhaps from `model.meta.filename`) was assigned to that attribute. For example:

```python
>> m = rdm.open("some_roman_file.asdf")
>> m['foo'] = m.meta.filename
>> m.schema_info('archive_catalog')['roman']['foo']
{'archive_catalog': {'datatype': 'nvarchar(120)', 'destination': ['WFIExposure.filename', 'WFIMosaic.filename', 'GuideWindow.filename', 'WFICommon.filename', 'SourceCatalog.filename', 'SegmentationMap.filename']}}
```
The above output is expected as the filename object is not a string and has an associated schema with [archive_catalog](https://github.com/spacetelescope/rad/blob/2c353844b97de615a8f306145e0fbbbd5695c3f2/src/rad/resources/schemas/tagged_scalars/filename-1.0.0.yaml#L12) information.

Perhaps it makes sense to not use the asdf schemas for this information?

**Comment by braingram** [comment] 2024-07-20 19:52
Thanks for sharing the file (offline). It is confirmed that the above comment is the case and this is an issue for the code that produced the file. asdf is working as intended as the mentioned node in the tree has a schema with an `archive_catalog` attribute.

**Closed by braingram** 2024-07-20 19:52 UTC
