### ISSUE TITLE
Metadata don't distinguish between Fortran- and C-order arrays?

### ISSUE THREAD

**Issue by bilderbuchi** [asdf-format/asdf#1205] opened 2022-10-06 09:08 UTC
I am confused how the metadata seems to not indicate if an array is stored in column- or row-major order.
Based on #538, and triggered by [this HackerNews comment](https://news.ycombinator.com/item?id=33092662), I came up with this example:
```python
import numpy as np
import asdf

farray = np.array([[11,12,13], [21,22,23]], order='F')
carray = np.array([[11,12,13], [21,22,23]], order='C')
file = asdf.AsdfFile({"farray": farray, "carray": carray})
file.write_to("strides.asdf")

file2 = asdf.open("strides.asdf")

farray2 = file2.tree["farray"]
print("Original farray:\n", farray[:,:])
print("Recovered farray:\n", farray2[:,:])
carray2 = file2.tree["carray"]
print("Original carray:\n", carray[:,:])
print("Recovered carray:\n", carray2[:,:])
```
which, when running with current asdf from conda, successfully recovers the arrays correctly:
```
Original farray:
 [[11 12 13]
 [21 22 23]]
Recovered farray:
 [[11 12 13]
 [21 22 23]]
Original carray:
 [[11 12 13]
 [21 22 23]]
Recovered carray:
 [[11 12 13]
 [21 22 23]]
```

However, the header of the created file shows no indication that those two arrays have different order:
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, homepage: 'http://github.com/asdf-format/asdf',
  name: asdf, version: 2.13.0}
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension.BuiltinExtension
    software: !core/software-1.0.0 {name: asdf, version: 2.13.0}
carray: !core/ndarray-1.0.0
  source: 0
  datatype: int32
  byteorder: little
  shape: [2, 3]
farray: !core/ndarray-1.0.0
  source: 2
  datatype: int32
  byteorder: little
  shape: [2, 3]
...
```
How can this successfully round-trip arrays if the row/column-major information is not contained in the metadata? Is this using some numpy-specific thing (cf #827) when saving the contents to disk?

From [the standard](https://asdf.readthedocs.io/en/stable/asdf/arrays.html?highlight=strides#sharing-of-data), assuming it's _stored_ in C order, I would have expected that the F-array would have gotten a `strides` entry. 
If it's actually stored in F-order, how is a loading program able to determine that?
If the data is not stored in the order in which it was presented to asdf, does that have performance implications?

I didn't know if this is a standards-related issue or one of the Python implementation.

**Comment by perrygreenfield** [comment] 2022-10-06 11:52
Good question. I will have to look into this. Interestingly there are three blocks, but only two are referenced in the YAML and each of the blocks contains the array data, Twice in C order and once in F order (the F order one is the block not referenced). Offhand I don't understand why. Thanks for raising this.

**Comment by braingram** [comment] 2022-10-06 13:53
Thanks for sharing the details and code.

The to_tree method converts f order numpy arrays to c order prior to saving (relevant call to numpy.ascontiguous [here](https://github.com/asdf-format/asdf/blob/master/asdf/tags/core/ndarray.py#L421)). Testing your example on the current dev branch shows the same results you reported. Since the farray was converted to c order on save, the read back farray2 is c order (farray2.flags.fortran is False).

This doesn't explain why there are 3 blocks in the code and I'm also not sure if the conversion to c order is intended behavior. I'll keep looking into it.

**Comment by WilliamJamieson** [comment] 2022-10-07 14:32
@bilderbuchi, it looks like you actually stumbled across a bug in ASDF, which was fixed by PR #1206.

Could you pull the `master` branch of ASDF (we are looking at making a new release of ASDF soon) and look over how ASDF is now handling Fortran-ordered arrays? Please let us know if this resolves your issues/questions around Fortran-arrays.

**Comment by bilderbuchi** [comment] 2022-10-10 08:44
I can see that now there are 2 binary blocks instead of 3, and that the Fortran array got a `strides` metadata entry, so that part seems to be solved, great! :-)

The only question I still have is:
> If the data is not stored in the order in which it was presented to asdf, does that have performance implications?

See also the remark by @braingram 
> I'm also not sure if the conversion to c order is intended behavior.

Without having run benchmarks on this, I'm pretty sure iterating through arrays in the "wrong" order (row/column index first) normally spells disaster for performance, as the CPU can't go through contiguous memory locations in order.
Therefore, if you want to have good performance on saving/streaming/loading large arrays, it seems to me that observing that memory order is a good idea (tm). I'm wondering if only being able to store arrays in C-order will have a significant performance impact, so it might be worth it to keep this in mind when evolving the format?

*Note: currently I'm not personally having this need, my Fortran usage is not a good fit for asdf, but I would assume others will*

**Comment by braingram** [comment] 2022-10-10 13:04
I'm relatively new to the library and standard (only been working on it for 2 weeks) so my knowledge of what is intended vs actual behavior is incomplete :)

For this specific example (a f order and a c order array) the library saves and loads the data without manipulation (now that the bug is fixed, thanks again for finding it). For the f order array the data is stored as f order in the asdf block and loaded as f order (by using 'A' "any order" during the [ndarray creation](https://github.com/asdf-format/asdf/blob/master/asdf/tags/core/ndarray.py#L402)).

There are situations (like [non-contguous arrays](https://github.com/asdf-format/asdf/blob/master/asdf/tags/core/ndarray.py#L421)) where the array is copied and performance will suffer. Given the flexibility in ndarrays there are almost certainly situations where performance is sub-optimal.

I'm going to close the issue but feel free to reopen this or a new one if if you find anything else. Thanks again!

**Closed by braingram** 2022-10-10 13:04 UTC
Labels: bug
